- name: install lilyterm dependencies
  tags: lilyterm
  package:
    name:
      - libgtk-3-dev
      - libvte-dev

- name: download lilyterm source
  tags: lilyterm
  get_url:
    url: https://lilyterm.luna.com.tw/file/lilyterm-0.9.9.2.tar.gz
    dest: /usr/local/src/lilyterm-0.9.9.2.tar.gz
  register: lilyterm_source

- name: extract lilyterm source
  tags: lilyterm
  unarchive:
    src: /usr/local/src/lilyterm-0.9.9.2.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: lilyterm_source.changed
  register: lilyterm_source_unpack

- name: configure lilyterm source
  command: ./configure
  args:
    chdir: /usr/local/src/lilyterm-0.9.9.2
  when: lilyterm_source_unpack.changed
  register: lilyterm_configure

- name: install lilyterm
  become: yes
  shell: make && make install
  args:
    chdir: /usr/local/src/lilyterm-0.9.9.2
  when: lilyterm_configure.changed

- name: create lilyterm config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0770
  loop:
    - /home/ubuntu/.config
    - /home/ubuntu/.config/lilyterm

- name: copy lilyterm default.conf
  tags: lilyterm
  copy:
    src: lilyterm/default.conf
    dest: /home/ubuntu/.config/lilyterm/default.conf
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: download wallpaper
  tags: lilyterm
  get_url:
    url: https://sberts.com/wp.tar.gz
    dest: /usr/local/share
  register: wallpaper_download

- name: extract lilyterm wallpapers
  tags: lilyterm
  unarchive:
    src: /usr/local/share/wp.tar.gz
    dest: /usr/local/share
    remote_src: yes
  when: wallpaper_download.changed
  register: wallpaper_unpacked

- name: copy resize wallpaper script
  tags: lilyterm
  copy:
    src: lilyterm/resize-wp.sh
    dest: /usr/local/bin
    mode: '755'

- name: resize lilyterm wallpapers
  tags: lilyterm
  command: ./resizewp.sh
  args:
    chdir: /usr/local/bin
  when: wallpaper_unpacked.changed
  register: wallpaper_resized

- name: copy lilyterm conf script
  tags: lilyterm
  copy:
    src: lilyterm/lterm-conf.sh
    dest: /usr/local/bin
    mode: '755'

- name: generate lilyterm conf files
  tags: lilyterm
  command: ./lterm-conf.sh
  args:
    chdir: /usr/local/bin
  when: wallpaper_resized.changed

- name: copy lilyterm script
  tags: lilyterm
  copy:
    src: lilyterm/lterm.sh
    dest: /usr/local/bin
    mode: '755'
