- name: install cloudpackages
  tags: cloud
  package:
    name:
      - python3-openstackclient
      - python3-neutronstackclient
      - python3-glancestackclient

- name: download terraform source
  tags: cloud
  get_url:
    url: https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
    dest: /usr/local/src/terraform_1.0.11_linux_amd64.zip
  register: terraform_source

- name: extract terraform source
  tags: cloud
  unarchive:
    src: /usr/local/src/terraform_1.0.11_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: terraform_source.changed

- name: download aws-cli
  tags: cloud 
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /usr/local/src/awscli-exe-linux-x86_64.zip
  register: awscli_source

- name: extract aws-cli
  tags: cloud
  unarchive:
    src: /usr/local/src/awscli-exe-linux-x86_64.zip
    dest: /usr/local/src
    remote_src: yes
  when: awscli_source.changed
  register: awscli_source_unpack

- name: install aws-cli
  tags: cloud
  command: ./install
  args:
    chdir: /usr/local/src/aws
  when: awscli_source_unpack.changed

- name: add aws cli command completion
  tags: cloud
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: complete -C '/usr/local/bin/aws_completer' aws

- name: download aws-sam-cli
  tags: cloud 
  get_url:
    url: https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
    dest: /usr/local/src/aws-sam-cli-linux-x86_64.zip
  register: awssamcli_source

- name: extract aws-sam-cli
  tags: cloud
  unarchive:
    src: /usr/local/src/aws-sam-cli-linux-x86_64.zip
    dest: /usr/local/src/sam-installation
    remote_src: yes
  when: awssamcli_source.changed
  register: awssamcli_source_unpack

- name: install aws-sam-cli
  tags: cloud
  command: ./install
  args:
    chdir: /usr/local/src/sam-installation
  when: awssamcli_source_unpack.changed

