- name: Add Docker GPG apt Key
  tags: docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  tags: docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  tags: docker
  apt: update_cache=yes name=docker-ce state=latest

- name: add ubuntu user to docker group
  tags: docker
  user:
    name: ubuntu
    groups: docker
    append: yes
