- name: install base packages
  tags: packages
  package:
    name:
      - htop
      - tmux
      - vim-nox
      - python3-pip
      - nodejs
  
- name: install base pip packages
  pip:
    name:
      - bpytop
      - powerline-status

- name: insert powerline.sh into .bashrc
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: . /usr/local/lib/python3.8/dist-packages/powerline/bindings/bash/powerline.sh

- name: add powerline tmux config
  copy:
    dest: /home/ubuntu/.tmux.conf
    owner: ubuntu
    content: |
      run-shell "powerline-daemon -q"
      source "/usr/local/lib/python3.8/dist-packages/powerline/bindings/tmux/powerline.conf"
