- name: install base packages
  tags: packages
  package:
    name:
      - htop
      - tmux
      - vim-nox
      - python3-pip
      - nodejs
  
- name: install bpytop
  pip:
    name:
      - bpytop
      - powerline-status

- name: insert powerline.sh into .bashrc
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: . /usr/local/lib/python3.8/dist-packages/powerline/bindings/bash/powerline.sh
