- name: create i3 directories
  tags: i3
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0770
  loop:
    - /home/ubuntu/.config
    - /home/ubuntu/.config/i3

- name: copy i3 config
  tags: i3
  copy:
    src: i3/config
    dest: /home/ubuntu/.config/i3/config
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: start graphical desktop
  command: systemctl isolate graphical.target

- name: set graphical desktop to start on boot
  command: systemctl set-default graphical.target
